In [1]:
import requests
import json
import pandas as pd

In [2]:
base_url = "https://data.police.uk/api/stops-street?"
location = "lat=51.5072&lng=-0.1276&date="
dates = ["2021-01","2021-02","2021-03","2021-04","2021-05"]

In [3]:
jan_may = []
for date in dates:
    query_url = base_url + location + date
    response = requests.get(query_url).json()
    jan_may.append(response)

In [4]:
london_data = pd.DataFrame.from_dict(jan_may[0])
london_data = london_data.append(pd.DataFrame.from_dict(jan_may[1]))
london_data = london_data.append(pd.DataFrame.from_dict(jan_may[2]))
london_data = london_data.append(pd.DataFrame.from_dict(jan_may[3]))
london_data = london_data.append(pd.DataFrame.from_dict(jan_may[4]))
london_data.head()

,age_range,outcome,involved_person,self_defined_ethnicity,gender,legislation,outcome_linked_to_object_of_search,datetime,removal_of_more_than_outer_clothing,outcome_object,location,operation,officer_defined_ethnicity,type,operation_name,object_of_search
0,18-24,A no further action disposal,True,Other ethnic group - Not stated,Male,Misuse of Drugs Act 1971 (section 23),True,2021-01-01T04:07:00+00:00,False,"{'id': 'bu-no-further-action', 'name': 'A no f...","{'latitude': '51.510100', 'street': {'id': 148...",None,Black,Person search,None,Controlled drugs
1,25-34,A no further action disposal,True,Other ethnic group - Not stated,Male,Police and Criminal Evidence Act 1984 (section 1),False,2021-01-03T19:50:00+00:00,False,"{'id': 'bu-no-further-action', 'name': 'A no f...","{'latitude': '51.503381', 'street': {'id': 149...",None,White,Person search,None,Offensive weapons
2,10-17,A no further action disposal,True,White - English/Welsh/Scottish/Northern Irish/...,Male,Misuse of Drugs Act 1971 (section 23),True,2021-01-04T17:17:00+00:00,False,"{'id': 'bu-no-further-action', 'name': 'A no f...","{'latitude': '51.503381', 'street': {'id': 149...",None,White,Person search,None,Controlled drugs
3,10-17,A no further action disposal,True,White - English/Welsh/Scottish/Northern Irish/...,Male,Misuse of Drugs Act 1971 (section 23),False,2021-01-04T16:20:00+00:00,False,"{'id': 'bu-no-further-action', 'name': 'A no f...","{'latitude': '51.503381', 'street': {'id': 149...",None,White,Person search,None,Controlled drugs
4,over 34,A no further action disposal,True,Black/African/Caribbean/Black British - African,Male,Police and Criminal Evidence Act 1984 (section 1),False,2021-01-04T21:00:00+00:00,False,"{'id': 'bu-no-further-action', 'name': 'A no f...","{'latitude': '51.503381', 'street': {'id': 149...",None,Black,Person search,None,Stolen goods

In [5]:
london_info = london_data[["age_range", "self_defined_ethnicity", "gender", "officer_defined_ethnicity", "object_of_search", "location"]]
london_info.head()

,age_range,self_defined_ethnicity,gender,officer_defined_ethnicity,object_of_search,location
0,18-24,Other ethnic group - Not stated,Male,Black,Controlled drugs,"{'latitude': '51.510100', 'street': {'id': 148..."
1,25-34,Other ethnic group - Not stated,Male,White,Offensive weapons,"{'latitude': '51.503381', 'street': {'id': 149..."
2,10-17,White - English/Welsh/Scottish/Northern Irish/...,Male,White,Controlled drugs,"{'latitude': '51.503381', 'street': {'id': 149..."
3,10-17,White - English/Welsh/Scottish/Northern Irish/...,Male,White,Controlled drugs,"{'latitude': '51.503381', 'street': {'id': 149..."
4,over 34,Black/African/Caribbean/Black British - African,Male,Black,Stolen goods,"{'latitude': '51.503381', 'street': {'id': 149..."

In [6]:
london_info['country'] = 'london'

<ipython-input-6-58e5db83b615>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  london_info['country'] = 'london'

In [7]:
london_info.set_index('country', inplace=True)
london_info.head()

,age_range,self_defined_ethnicity,gender,officer_defined_ethnicity,object_of_search,location
country,,,,,,
london,18-24,Other ethnic group - Not stated,Male,Black,Controlled drugs,"{'latitude': '51.510100', 'street': {'id': 148..."
london,25-34,Other ethnic group - Not stated,Male,White,Offensive weapons,"{'latitude': '51.503381', 'street': {'id': 149..."
london,10-17,White - English/Welsh/Scottish/Northern Irish/...,Male,White,Controlled drugs,"{'latitude': '51.503381', 'street': {'id': 149..."
london,10-17,White - English/Welsh/Scottish/Northern Irish/...,Male,White,Controlled drugs,"{'latitude': '51.503381', 'street': {'id': 149..."
london,over 34,Black/African/Caribbean/Black British - African,Male,Black,Stolen goods,"{'latitude': '51.503381', 'street': {'id': 149..."

In [8]:
age_range = london_info["age_range"]
age_range.groupby(age_range).count()

age_range
10-17       442
18-24      1119
25-34       802
over 34     580
Name: age_range, dtype: int64

In [9]:
outcome = london_info["object_of_search"]
outcome.groupby(outcome).count()

object_of_search
Anything to threaten or harm anyone      58
Article for use in theft                  9
Articles for use in criminal damage      51
Controlled drugs                       2070
Evidence of offences under the Act      119
Firearms                                  3
Fireworks                                 6
Offensive weapons                       359
Stolen goods                            766
Name: object_of_search, dtype: int64

In [10]:
self_defined_ethnicity = london_info["self_defined_ethnicity"]
self_defined_ethnicity.groupby(self_defined_ethnicity).count()

self_defined_ethnicity
Asian/Asian British - Any other Asian background                                         125
Asian/Asian British - Bangladeshi                                                         41
Asian/Asian British - Chinese                                                             11
Asian/Asian British - Indian                                                              51
Asian/Asian British - Pakistani                                                           41
Black/African/Caribbean/Black British - African                                          207
Black/African/Caribbean/Black British - Any other Black/African/Caribbean background     260
Black/African/Caribbean/Black British - Caribbean                                         88
Mixed/Multiple ethnic groups - Any other Mixed/Multiple ethnic background                 80
Mixed/Multiple ethnic groups - White and Asian                                             9
Mixed/Multiple ethnic groups - White and Black African                                    11
Mixed/Multiple ethnic groups - White and Black Caribbean                                  31
Other ethnic group - Any other ethnic group                                              165
Other ethnic group - Not stated                                                         1061
White - Any other White background                                                       479
White - English/Welsh/Scottish/Northern Irish/British                                    737
White - Irish                                                                             33
Name: self_defined_ethnicity, dtype: int64

In [11]:
officer_defined_ethnicity = london_info["officer_defined_ethnicity"]
officer_defined_ethnicity.groupby(officer_defined_ethnicity).count()

officer_defined_ethnicity
Asian     384
Black     930
Other     305
White    1752
Name: officer_defined_ethnicity, dtype: int64

In [12]:
gender = london_info["gender"]
gender.groupby(gender).count()

gender
Female     340
Male      3069
Other        6
Name: gender, dtype: int64

In [13]:
london_info.to_csv("data/london.csv")